(in-package :ggs/stochastic)

(defun subst-row (new old pat-row)
  (append (butlast pat-row)
          (list `(let ((,old ,new))
                   (declare (ignorable ,old))
                   ,(lastcar pat-row)))))

(defmacro case/bind (keyform &body cases)
  "Like CASE, but also support ((?VAR) ...) clauses, which run before
everything else and bind ?VAR."
  (multiple-value-bind (bind-clauses real-cases)
      (partition (lambda (case) (and (consp (car case)) (var-p (caar case))))
                 cases)
    (let ((bind-forms (mapcar (lambda (clause)
                                `(let ((,(caar clause) ,keyform))
                                   ,@(cdr clause)))
                              bind-clauses)))
      (cond ((and bind-forms real-cases)
             `(progn ,@bind-forms (case ,keyform ,@real-cases)))
            (bind-forms `(progn ,@bind-forms))
            (real-cases `(case ,keyform ,@real-cases))))))

(defun expand-match (var-list pat-mat)
  (unless var-list
    (return-from expand-match
      (mapcar #'serapeum:only-elt pat-mat)))
  ;; pattern column selection heuristics
  (when pat-mat
    (setq pat-mat (copy-tree pat-mat)
          var-list (copy-list var-list))
    (let* ((columns (butlast (apply #'mapcar #'list pat-mat)))
           (column-n-tested (mapcar (lambda (c)
                                      (count-if-not #'var-p (mapcar #'ensure-car c)))
                                    columns))
           (selected (position (reduce #'max column-n-tested)
                               column-n-tested)))
      (rotatef (car var-list) (nth selected var-list))
      (mapc (lambda (row)
              (rotatef (car row) (nth selected row)))
            pat-mat)))
  (let ((groups (make-hash-table))
        (var (car var-list))
        bind-rows
        node-clauses
        atom-clauses)
    (dolist (pat-row pat-mat)
      (let ((pat (car pat-row)))
        (cond ((consp pat)
               (push pat-row (gethash (car pat) groups)))
              ((var-p pat)
               (push pat-row bind-rows))
              (t
               (push pat-row (gethash pat groups))))))
    (maphash-values
     (lambda (pat-rows)
       (let* ((sample (ensure-list (caar pat-rows)))
              (fsym (car sample))
              (arg-vars (make-gensym-list (length (cdr sample))
                                          (prin1-to-string fsym))))
         (if arg-vars
             (push `((,fsym)
                     (when (= (rose-node-n-args ,var) ,(length arg-vars))
                       (let ,(mapcar (lambda (i arg-var)
                                       `(,arg-var (rose-node-arg ,i ,var)))
                                     (iota (length arg-vars)) arg-vars)
                         ,@(expand-match
                            (append arg-vars (cdr var-list))
                            (mapcar (lambda (pat-row)
                                      (append (cdr (ensure-list (car pat-row)))
                                              (cdr pat-row)))
                                    pat-rows)))))
                   node-clauses)
             (push `((,fsym)
                     ,@(expand-match
                        (cdr var-list)
                        (mapcar #'cdr pat-rows)))
                   atom-clauses))))
     groups)
    (append
     (expand-match
      (cdr var-list)
      (mapcar (lambda (pat-row)
                (subst-row var (car pat-row) (cdr pat-row)))
              bind-rows))
     (when (or node-clauses atom-clauses)
       `((if (rose-node-p ,var)
             (case/bind (rose-node-fsym ,var) ,@node-clauses)
             (case/bind ,var ,@atom-clauses)))))))

(defun expand-template (tmpl cost-fn user-decls)
  (labels ((process (tmpl)
             (cond ((and (consp tmpl) (eql (car tmpl) :eval))
                    `(locally (declare ,@user-decls) ,(cadr tmpl)))
                   ((consp tmpl)
                    `(let ((new-node
                             (vector 0.0 -1 1 ',(car tmpl)
                                     ,@(mapcar #'process (cdr tmpl)))))
                       (setf (rose-node-cost new-node) (,cost-fn new-node))
                       new-node))
                   ((var-p tmpl) tmpl)
                   (t `',tmpl))))
    (process tmpl)))

(defun node-equal (x y)
  (labels ((process (x y)
             (cond
               ((and (not (rose-node-p x)) (not (rose-node-p y))) (eql x y))
               ((and (rose-node-p x) (rose-node-p y))
                (unless (= (length x) (length y))
                  (return-from node-equal nil))
                (loop for i from (1- +rose-node-args-offset+) below (length x)
                      always (node-equal (svref x i) (svref y i)))))))
    (process x y)))

(defun decompose-consistency-check (pat cont-expr)
  (let (vars checks)
    (labels ((process (pat)
               (cond ((consp pat)
                      (cons (car pat)
                            (mapcar #'process (cdr pat))))
                     ((var-p pat)
                      (if (member pat vars)
                          (let ((new-var (gensym-1 pat)))
                            (push `(node-equal ,pat ,new-var) checks)
                            new-var)
                          (progn
                            (push pat vars)
                            pat)))
                     (t pat))))
      (values (process pat)
              `(when (and ,@checks)
                 ,cont-expr)))))

(defmacro do-matches* (top-node-var &body clauses)
  `(progn ,@(expand-match
             (list top-node-var)
             (mapcar (lambda (clause)
                       (bind (((pat . body) clause))
                             (multiple-value-list
                              (decompose-consistency-check pat `(progn ,@body)))))
                     clauses))))
